-- Add IDENTITY to provider payables tables (fix for null PK on insert)

ALTER TABLE provider_payables
    ALTER COLUMN provider_payable_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('provider_payables', 'provider_payable_id'),
    GREATEST(COALESCE((SELECT MAX(provider_payable_id) FROM provider_payables), 0), 1)
);

ALTER TABLE provider_payable_lines
    ALTER COLUMN provider_payable_line_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('provider_payable_lines', 'provider_payable_line_id'),
    GREATEST(COALESCE((SELECT MAX(provider_payable_line_id) FROM provider_payable_lines), 0), 1)
);

ALTER TABLE provider_payable_transactions
    ALTER COLUMN provider_payable_transaction_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('provider_payable_transactions', 'provider_payable_transaction_id'),
    GREATEST(COALESCE((SELECT MAX(provider_payable_transaction_id) FROM provider_payable_transactions), 0), 1)
);
